name: async_field
description: Async fields that can be stored or fetched from any source (databases, web services, local storage or other thread/isolate), with observable values, caches and stale versions.
version: 1.0.8
homepage: https://github.com/eneural-net/async_field

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  async_extension: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
