name: async_field
description: Async fields that can be stored or fetched from any source (databases, web services, local storage or other thread/isolate), with observable values, caches and stale versions.
version: 1.1.0
homepage: https://github.com/eneural-net/async_field

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  async_extension: ^1.2.12

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
  dependency_validator: ^3.2.3
  coverage: ^1.8.0
